server:
  port: 9000

logging:
  level:
    es.in2: info

spring:
  application:
    name: VC Verifier
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/resources/

security:
  authorizationServer:
  token:
    accessToken:
      cronUnit:
      expiration:

trust-framework:
  issuersListUri:
  participantsListUri:
  clientsListUri:

crypto:
  privateKey: